In [1]:
#Imports required libraries.
import pandas as pd

In [2]:
#Using Pandas library to read the csv file.This stores CSV file in ram.Dynamically stored.
conversions=pd.read_csv("conversions.csv.xls")

In [ ]:
#head() function is used to see first few rows of csv file.
conversions.head()

  user_id      conversion_date  revenue
0  U00001  2025-05-15 09:56:35   427.99
1  U00005  2025-02-24 19:28:00   470.38
2  U00006  2025-04-26 04:32:00   853.58
3  U00008  2025-06-23 04:00:04   790.46
4  U00009  2025-06-13 17:55:21   385.54

In [ ]:
#Similar to head() , but retreives a random sample of rows for examining. 
conversions.sample(5)

     user_id conversion_date  revenue
746   U04712      2025-04-16   586.80
1154  U07236      2025-05-09    80.26
84    U00524      2025-02-12   174.82
372   U02358      2025-06-15   468.65
248   U01692      2025-01-26   442.70

In [ ]:
#Using info() function helps understand data
#Can verify Columns, total columns, Non-Null Columns, Datatypes
conversions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1564 entries, 0 to 1563
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          1564 non-null   str
 1   conversion_date  1564 non-null   str
 2   revenue          1564 non-null   float64
dtypes: float64(1), str(2)
memory usage: 36.8 KB

In [5]:
#Describe() functions gives a statistical Summary of the dataframe.
conversions.describe()

           revenue
count  1564.000000
mean    641.044987
std     329.734181
min      75.770000
25%     363.585000
50%     637.220000
75%     929.212500
max    1199.430000

In [ ]:
#Converting Conversion_date column from str datatype to datetime dataype.
conversions['conversion_date'] = pd.to_datetime(conversions['conversion_date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
conversions['conversion_date'] = conversions['conversion_date'].dt.normalize()

In [ ]:
#Checking Duplicates.
print("Duplicate rows:", conversions.duplicated().sum())

Duplicate rows: 0

In [16]:
#Checking missing values.
print(conversions.isnull().sum())

user_id            0
conversion_date    0
revenue            0
dtype: int64