In [1]:
import pandas as pd

In [2]:
conversions=pd.read_csv("conversions.csv.xls")

In [3]:
conversions.head()

  user_id      conversion_date  revenue
0  U00001  2025-05-15 09:56:35   427.99
1  U00005  2025-02-24 19:28:00   470.38
2  U00006  2025-04-26 04:32:00   853.58
3  U00008  2025-06-23 04:00:04   790.46
4  U00009  2025-06-13 17:55:21   385.54

In [4]:
conversions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1564 entries, 0 to 1563
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          1564 non-null   str
 1   conversion_date  1564 non-null   str
 2   revenue          1564 non-null   float64
dtypes: float64(1), str(2)
memory usage: 36.8 KB

In [5]:
conversions.describe()

           revenue
count  1564.000000
mean    641.044987
std     329.734181
min      75.770000
25%     363.585000
50%     637.220000
75%     929.212500
max    1199.430000

In [8]:
conversions['conversion_date'] = pd.to_datetime(conversions['conversion_date'])

conversions['conversion_date'] = conversions['conversion_date'].dt.normalize()

In [7]:
conversions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1564 entries, 0 to 1563
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          1564 non-null   str
 1   conversion_date  1564 non-null   datetime64[us]
 2   revenue          1564 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 36.8 KB