In [7]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
#Reading CSV file
adspend=pd.read_csv("/workspaces/Multi-Touch-Marketing-Attribution-ROI-Dashboard/Raw_Data/ad_spend.csv.xls")

In [16]:
print(adspend)

           date         channel            campaign    spend
0    2025-01-01      Google Ads   Competitor Search  2185.43
1    2025-01-01    Facebook Ads         Winter Sale  4778.21
2    2025-01-01      TikTok Ads     Influencer Push  3793.97
3    2025-01-01  Organic Search     Organic Landing     0.00
4    2025-01-02      Google Ads        Brand Search  3193.96
..          ...             ...                 ...      ...
719  2025-06-29  Organic Search            SEO Blog     0.00
720  2025-06-30      Google Ads        Brand Search  4793.23
721  2025-06-30    Facebook Ads  Lookalike Audience  3227.79
722  2025-06-30      TikTok Ads     Awareness Blast  1528.89
723  2025-06-30  Organic Search            SEO Blog     0.00

[724 rows x 4 columns]

In [9]:
adspend.head()

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [11]:
adspend.sample(5)

           date         channel         campaign    spend
206  2025-02-21      TikTok Ads     UGC Campaign  1589.25
272  2025-03-10      Google Ads   Generic Search  3228.93
201  2025-02-20    Facebook Ads      Winter Sale  1578.03
223  2025-02-25  Organic Search  Organic Landing     0.00
123  2025-01-31  Organic Search         SEO Blog     0.00

In [ ]:
#Statistical Analysis
adspend.describe()

             spend
count   724.000000
mean   2086.547196
std    1680.412533
min       0.000000
25%     392.085000
50%    1971.645000
75%    3610.297500
max    4998.730000