In [1]:
#Imports required libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Using Pandas library to read the csv file.This stores CSV file in ram.Dynamically stored.
customer=pd.read_csv("/workspaces/Multi-Touch-Marketing-Attribution-ROI-Dashboard/Raw_Data/dim_customer.csv.xls")

In [3]:
#head() function is used to see first few rows of csv file.
customer.head()

,customer_key,user_id,region,primary_device,first_touch_date,last_touch_date,total_touchpoints,conversion_flag,conversion_date,customer_lifetime_revenue,acquisition_channel,acquisition_campaign
0,1,U00001,North America,Desktop,2025-05-14 18:56:35,2025-05-16 12:56:00,2,True,2025-05-15 09:56:35,427.99,Organic Search,Organic Landing
1,2,U00002,North America,Desktop,2025-04-04 15:58:00,2025-04-09 10:58:50,2,False,NaN,0.00,TikTok Ads,UGC Campaign
2,3,U00003,Asia Pacific,Tablet,2025-01-23 07:05:32,2025-02-02 02:05:32,4,False,NaN,0.00,Organic Search,Organic Landing
3,4,U00004,Asia Pacific,Mobile,2025-02-10 11:39:23,2025-02-12 19:39:00,2,False,NaN,0.00,Organic Search,SEO Blog
4,5,U00005,Asia Pacific,Tablet,2025-02-21 15:28:06,2025-02-21 22:28:00,2,True,2025-02-24 19:28:00,470.38,Google Ads,Competitor Search

In [4]:
#Similar to head() , but retreives a random sample of rows for examining. 
customer.sample(5)

,customer_key,user_id,region,primary_device,first_touch_date,last_touch_date,total_touchpoints,conversion_flag,conversion_date,customer_lifetime_revenue,acquisition_channel,acquisition_campaign
5852,5853,U05853,Asia Pacific,Mobile,2025-06-13 14:50:00,2025-06-20 02:50:10,4,False,NaN,0.0,Organic Search,Organic Landing
3745,3746,U03746,North America,Tablet,2025-06-17 05:23:18,2025-06-21 22:23:00,3,False,NaN,0.0,Organic Search,SEO Blog
5767,5768,U05768,Asia Pacific,Mobile,2025-04-29 18:32:00,2025-05-14 17:32:00,6,False,NaN,0.0,Organic Search,SEO Blog
9203,9204,U09204,Europe,Desktop,2025-04-09 14:27:05,2025-04-12 10:27:05,4,False,NaN,0.0,Organic Search,Organic Landing
4520,4521,U04521,Asia Pacific,Tablet,2025-04-08 03:34:00,2025-04-09 12:34:00,2,False,NaN,0.0,TikTok Ads,Influencer Push

In [5]:
#Using info() function helps understand data
#Can verify Columns, total columns, Non-Null Columns, Datatypes
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_key               10000 non-null  int64
 1   user_id                    10000 non-null  str
 2   region                     10000 non-null  str
 3   primary_device             10000 non-null  str
 4   first_touch_date           10000 non-null  str
 5   last_touch_date            10000 non-null  str
 6   total_touchpoints          10000 non-null  int64
 7   conversion_flag            10000 non-null  bool
 8   conversion_date            1564 non-null   str
 9   customer_lifetime_revenue  10000 non-null  float64
 10  acquisition_channel        10000 non-null  str
 11  acquisition_campaign       10000 non-null  str
dtypes: bool(1), float64(1), int64(2), str(8)
memory usage: 869.3 KB

In [ ]:
#Describe() functions gives a statistical Summary of the dataframe.
customer.describe()

In [7]:
#Converting customer['first_touch_date'] column from str datatype to datetime dataype.
customer['first_touch_date'] = pd.to_datetime(customer['first_touch_date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
customer['first_touch_date'] = customer['first_touch_date'].dt.normalize()

In [9]:
#Converting customer['last_touch_date'] column from str datatype to datetime dataype.
customer['last_touch_date'] = pd.to_datetime(customer['last_touch_date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
customer['last_touch_date'] = customer['last_touch_date'].dt.normalize()

In [10]:
#Converting customer['conversion_date'] column from str datatype to datetime dataype.
customer['conversion_date'] = pd.to_datetime(customer['conversion_date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
customer['conversion_date'] = customer['conversion_date'].dt.normalize()

In [11]:
#Using info() function helps understand data
#Can verify Columns, total columns, Non-Null Columns, Datatypes
#Using this particular line to check if the datatype is changed from str to datetime
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_key               10000 non-null  int64
 1   user_id                    10000 non-null  str
 2   region                     10000 non-null  str
 3   primary_device             10000 non-null  str
 4   first_touch_date           10000 non-null  datetime64[us]
 5   last_touch_date            10000 non-null  datetime64[us]
 6   total_touchpoints          10000 non-null  int64
 7   conversion_flag            10000 non-null  bool
 8   conversion_date            1564 non-null   datetime64[us]
 9   customer_lifetime_revenue  10000 non-null  float64
 10  acquisition_channel        10000 non-null  str
 11  acquisition_campaign       10000 non-null  str
dtypes: bool(1), datetime64[us](3), float64(1), int64(2), str(5)
memory usage: 869.3 KB

In [12]:
#Checking Duplicates.
print("Duplicate rows:", customer.duplicated().sum())

Duplicate rows: 0

In [13]:
#Checking missing values.
print(customer.isnull().sum())

customer_key                    0
user_id                         0
region                          0
primary_device                  0
first_touch_date                0
last_touch_date                 0
total_touchpoints               0
conversion_flag                 0
conversion_date              8436
customer_lifetime_revenue       0
acquisition_channel             0
acquisition_campaign            0
dtype: int64