In [1]:
import sqlite3

conn = sqlite3.connect("marketing.db")

print("Connected successfully!")

conn.close()

Connected successfully!

In [6]:
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os

In [7]:
conn = sqlite3.connect("marketing.db")

In [3]:
def load_dataset(file_path, parse_dates=None):
    return pd.read_csv(file_path, parse_dates=parse_dates)

In [4]:
Clean_Adspend = load_dataset(
    "../data/cleaned_data/cleaned_Adspend_Table.csv",
    parse_dates=["date"]
)

Clean_Weblogs = load_dataset(
    "../data/cleaned_data/cleaned_User_Weblogs.csv",
    parse_dates=["timestamp"]
)

Clean_Customer = load_dataset(
    "../data/cleaned_data/cleaned_Customer_Table.csv",
    parse_dates=[
        "first_touch_date",
        "last_touch_date",
        "conversion_date"
    ]
)

Clean_Conversion = load_dataset(
    "../data/cleaned_data/cleaned_Conversion_Table.csv",
    parse_dates=["conversion_date"]
)

In [12]:
Clean_Weblogs.to_sql(
    "user_weblogs",
    conn,
    if_exists="replace",
    index=False
)

Clean_Conversion.to_sql(
    "conversions",
    conn,
    if_exists="replace",
    index=False
)

Clean_Adspend.to_sql(
    "ad_spend",
    conn,
    if_exists="replace",
    index=False
)

Clean_Customer.to_sql(
    "Customer",
    conn,
    if_exists="replace",
    index=False
)

10000

In [13]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

           name
0  user_weblogs
1   conversions
2      ad_spend
3      Customer

In [16]:

query = """
SELECT *
FROM user_weblogs;
"""

df = pd.read_sql(query, conn)

df.head()

,user_id,timestamp,region,device,channel,campaign,event_type,utm_source,utm_medium,utm_campaign,quarter,month_name,day_name,day_of_week,week,hour,is_weekend
0,U00001,2025-05-14 18:56:35+00:00,North America,Desktop,Organic,Organic Landing,Visit,organic_search,organic,Organic Landing,2.0,May,Wednesday,2.0,20.0,18.0,0
1,U00001,None,North America,Desktop,Tiktok Ads,Influencer Push,Product View,tiktok_ads,social,Influencer Push,NaN,None,None,NaN,NaN,NaN,0
2,U00002,None,North America,Desktop,Tiktok Ads,UGC Campaign,Product View,tiktok_ads,organic,UGC Campaign,NaN,None,None,NaN,NaN,NaN,0
3,U00002,2025-04-09 10:58:50+00:00,North America,Desktop,Facebook Ads,Retargeting,Visit,facebook_ads,organic,Retargeting,2.0,April,Wednesday,2.0,15.0,10.0,0
4,U00003,2025-01-23 07:05:32+00:00,Asia Pacific,Tablet,Organic,Organic Landing,Product View,organic_search,organic,Organic Landing,1.0,January,Thursday,3.0,4.0,7.0,0

In [18]:

query = """
SELECT *
FROM ad_spend;
"""

df = pd.read_sql(query, conn)

df.head()

,date,channel,campaign,spend,date_quarter,date_month_name,date_day_name,date_day_of_week,date_week,date_hour,date_is_weekend
0,2025-01-01 00:00:00+00:00,Google Ads,Competitor Search,2185.43,1,January,Wednesday,2,1,0,0
1,2025-01-01 00:00:00+00:00,Facebook Ads,Winter Sale,4778.21,1,January,Wednesday,2,1,0,0
2,2025-01-01 00:00:00+00:00,Tiktok Ads,Influencer Push,3793.97,1,January,Wednesday,2,1,0,0
3,2025-01-01 00:00:00+00:00,Organic,Organic Landing,0.00,1,January,Wednesday,2,1,0,0
4,2025-01-02 00:00:00+00:00,Google Ads,Brand Search,3193.96,1,January,Thursday,3,1,0,0

In [19]:

query = """
SELECT *
FROM conversions;
"""

df = pd.read_sql(query, conn)

df.head()

,user_id,conversion_date,revenue,conversion_date_quarter,conversion_date_month_name,conversion_date_day_name,conversion_date_day_of_week,conversion_date_week,conversion_date_hour,conversion_date_is_weekend
0,U00001,2025-05-15 09:56:35+00:00,427.99,2,May,Thursday,3,20,9,0
1,U00005,2025-02-24 19:28:00+00:00,470.38,1,February,Monday,0,9,19,0
2,U00006,2025-04-26 04:32:00+00:00,853.58,2,April,Saturday,5,17,4,1
3,U00008,2025-06-23 04:00:04+00:00,790.46,2,June,Monday,0,26,4,0
4,U00009,2025-06-13 17:55:21+00:00,385.54,2,June,Friday,4,24,17,0

In [21]:

query = """
SELECT *
FROM customer;
"""

df = pd.read_sql(query, conn)

df.head()

,customer_key,user_id,region,primary_device,first_touch_date,last_touch_date,total_touchpoints,conversion_flag,conversion_date,revenue,...,last_touch_date_week,last_touch_date_hour,last_touch_date_is_weekend,conversion_date_quarter,conversion_date_month_name,conversion_date_day_name,conversion_date_day_of_week,conversion_date_week,conversion_date_hour,conversion_date_is_weekend
0,1,U00001,North America,Desktop,2025-05-14 18:56:35+00:00,2025-05-16 12:56:00+00:00,2,1,2025-05-15 09:56:35+00:00,427.99,...,20,12,0,2.0,May,Thursday,3.0,20.0,9.0,0
1,2,U00002,North America,Desktop,2025-04-04 15:58:00+00:00,2025-04-09 10:58:50+00:00,2,0,None,0.00,...,15,10,0,NaN,None,None,NaN,NaN,NaN,0
2,3,U00003,Asia Pacific,Tablet,2025-01-23 07:05:32+00:00,2025-02-02 02:05:32+00:00,4,0,None,0.00,...,5,2,1,NaN,None,None,NaN,NaN,NaN,0
3,4,U00004,Asia Pacific,Mobile,2025-02-10 11:39:23+00:00,2025-02-12 19:39:00+00:00,2,0,None,0.00,...,7,19,0,NaN,None,None,NaN,NaN,NaN,0
4,5,U00005,Asia Pacific,Tablet,2025-02-21 15:28:06+00:00,2025-02-21 22:28:00+00:00,2,1,2025-02-24 19:28:00+00:00,470.38,...,8,22,0,1.0,February,Monday,0.0,9.0,19.0,0

In [ ]:
SELECT
    user_id,
    timestamp,
    channel,
    campaign,

    ROW_NUMBER() OVER(
        PARTITION BY user_id
        ORDER BY timestamp
    ) AS touch_order

FROM user_weblogs;

IndentationError: unexpected indent (506722779.py, line 2)